language: go
go: 1.9.2
env:
  global:
  - PATH=/home/travis/gopath/bin:$PATH
  - GHREPO_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - LINUXX64_ARCHIVENAME=${GHREPO_NAME}_x86_64-pc-linux-gnu_${TRAVIS_TAG}
  - WINDOWS_ARCHIVENAME=${GHREPO_NAME}_i686-mingw32_${TRAVIS_TAG}
  - MACOSX_ARCHIVENAME=${GHREPO_NAME}_x86_64-apple-darwin_${TRAVIS_TAG}
  - LINUXARM_ARCHIVENAME=${GHREPO_NAME}_arm-linux-gnueabihf_${TRAVIS_TAG}

deploy:
  provider: releases
  api_key:
    secure: G/W/8fL5CZwQQ4JuFPVOWOX3bj0koxVP3OAU47A7hnYp4IvimM6df2dk7I8Y7NFruLYHKI8FRjIyeBPnFd332pFDeBfXGcQajNv8BZ7N4VNWdrNwu1jNWiQyO7+pvu9cZ0DjfeMtvwFVvW2iL9h8ZnZEzRgdaaM+BE2qZkVckciXr3D/F4CsoorOw+a8eV48LRaqFeFwUkOesegLBKZvJ/qpjg6ZFe3RR0VeD62H3BFuGO1YeAYNmmjg86UhpVq+xRXWa3fgEP2YhEZvbLSUtiEIuT5vy1R3YJ+ZObXOH7DKdKSSW0A0y18301hIY+KyP/gWkj9608HVBr9/SnVjls2UfZR6z1W2pjv+BMmjUqfSIyavVWoma/sFG4xPrF6+xyGK+2GC6dLgIZKinlAyPovf+0JngnIZ4e1bWKEJY4J5z1yC7dcoTS6xA5IP9IcBGavKLzF7JVfJUUnx+au3jR8fiBecUNN5XWrzhqCXojusG9umTUjgUeOxfBXPZf5cXH25XvLZmW5gutVEviAHJukT7tmT4bcbumxPhLDDbzsintNTR3e6jSOhyeTDgXaeLXuAhbyHE9llNQsoHH5glLDdQFkGWJRWidKgmAwTb/P6Xjix+zepGvFdaeGP2LgFHVkP6rMPAYyL97RoCH98fGxs2DnWfpuCajced/AirnI=
  file:
    - "${LINUXX64_ARCHIVENAME}.tar.bz2"
    -  "${WINDOWS_ARCHIVENAME}.tar.bz2"
    -   "${MACOSX_ARCHIVENAME}.tar.bz2"
    - "${LINUXARM_ARCHIVENAME}.tar.bz2"
  skip_cleanup: true
  on:
    tags: true

install:

script:
- GOOS=linux   GOARCH=amd64 go build -o  pkg/linux_amd64/${GHREPO_NAME}/${GHREPO_NAME}
- GOOS=windows GOARCH=386   go build -o  pkg/windows_386/${GHREPO_NAME}/${GHREPO_NAME}.exe
- GOOS=darwin  GOARCH=amd64 go build -o pkg/darwin_amd64/${GHREPO_NAME}/${GHREPO_NAME}
- GOOS=linux   GOARCH=arm GOARM=6 go build -o  pkg/linux_arm7/${GHREPO_NAME}/${GHREPO_NAME}
- cp Makefile.template  pkg/linux_amd64/${GHREPO_NAME}
- cp Makefile.template  pkg/windows_386/${GHREPO_NAME}
- cp Makefile.template pkg/darwin_amd64/${GHREPO_NAME}
- cp Makefile.template   pkg/linux_arm7/${GHREPO_NAME}
- bash -c "cd  pkg/linux_amd64/ && tar cvfj ${PWD}/${LINUXX64_ARCHIVENAME}.tar.bz2 ${GHREPO_NAME}"
- bash -c "cd  pkg/windows_386/ && tar cvfj  ${PWD}/${WINDOWS_ARCHIVENAME}.tar.bz2 ${GHREPO_NAME}"
- bash -c "cd pkg/darwin_amd64/ && tar cvfj   ${PWD}/${MACOSX_ARCHIVENAME}.tar.bz2 ${GHREPO_NAME}"
- bash -c "cd   pkg/linux_arm7/ && tar cvfj ${PWD}/${LINUXARM_ARCHIVENAME}.tar.bz2 ${GHREPO_NAME}"
